import prisma from "~/server/utils/prisma";

export default defineEventHandler(async (event) => {
  try {
    const body = await readBody(event);
    
    // Validate required fields
    if (!body.vcs_vendor_code || !body.pom_request_by || !body.pom_request_date || !body.pom_document_no || !body.pom_description) {
      return {
        statusCode: 400,
        message: "Required fields are missing",
        data: null,
      };
    }
    
    // Get the current user from session (adjust based on your auth implementation)
    const user = event.context.user || { username: 'system' };
    
    // Create purchase order master
    const purchaseOrder = await prisma.purchase_order_master.create({
      data: {
        pom_order_no: null, // Will be generated by database or sequence
        pom_requisition_no: body.pom_requisition_no || null,
        pom_retrieve_type: body.pom_retrieve_type || null,
        org_code: body.org_code || null,
        vcs_vendor_code: body.vcs_vendor_code,
        pom_address: body.pom_deliver_address || null,
        pom_request_by: body.pom_request_by,
        pom_request_date: body.pom_request_date ? new Date(body.pom_request_date) : new Date(),
        pom_available_date: body.pom_estimate_delivery_date ? new Date(body.pom_estimate_delivery_date) : null,
        pom_ref_doc: body.pom_document_no,
        pom_description: body.pom_description,
        pom_doc_receive_date: body.pom_document_received_date ? new Date(body.pom_document_received_date) : null,
        pom_method: body.pom_purchase_method || null,
        pom_order_type: body.pom_purchase_type || null,
        pom_contact_person: body.pom_contact_person || null,
        pom_order_status: body.pom_order_status || 'DRAFT',
        pom_order_amt_rm: body.pom_total_amount ? parseFloat(body.pom_total_amount) : null,
        pom_discount_amt: body.pom_discount_amount ? parseFloat(body.pom_discount_amount) : null,
        pom_gross_amt: body.pom_gross_amt ? parseFloat(body.pom_gross_amt) : null,
        pom_order_amt: body.pom_order_amt ? parseFloat(body.pom_order_amt) : null,
        pom_total_paid: body.pom_total_paid ? parseFloat(body.pom_total_paid) : null,
        pom_total_invoiced: body.pom_total_invoiced ? parseFloat(body.pom_total_invoiced) : null,
        pom_total_tax: body.pom_total_tax ? parseFloat(body.pom_total_tax) : null,
        pom_currency_unit: body.pom_currency_unit ? parseFloat(body.pom_currency_unit) : null,
        pom_currency_code: body.pom_currency_code || null,
        pom_conversion_rate: body.pom_conversion_rate ? parseFloat(body.pom_conversion_rate) : null,
        pom_rate_type: body.pom_rate_type || null,
        pom_rate_date: body.pom_rate_date ? new Date(body.pom_rate_date) : null,
        pom_ent_amt: body.pom_ent_amt ? parseFloat(body.pom_ent_amt) : null,
        pom_exchange_type_code: body.pom_exchange_type_code || null,
        pom_shipto_id: body.pom_shipto_id || null,
        pom_aggrement_no: body.pom_aggrement_no || null,
        pom_order_ref: body.pom_order_ref || null,
        cpa_project_no: body.cpa_project_no || null,
        pom_wflow_sts: body.pom_wflow_sts || null,
        pom_wflow_type: body.pom_wflow_type || null,
        createdby: user.username || 'system',
        updatedby: user.username || 'system',
      },
    });
    
    // Create purchase order details if provided
    if (body.purchase_order_details && Array.isArray(body.purchase_order_details) && body.purchase_order_details.length > 0) {
      const detailsData = body.purchase_order_details.map((detail) => ({
        pom_order_id: purchaseOrder.pom_order_id,
        rqm_requisition_no: detail.rqm_requisition_no || null,
        bdg_budget_code: detail.bdg_budget_code || '',
        am_account_code: detail.am_account_code || '',
        pod_line_no: detail.pod_line_no ? parseFloat(detail.pod_line_no) : 0,
        itm_item_code: detail.itm_item_code || null,
        oun_code: detail.oun_code || null,
        pod_order_qty: detail.pod_order_qty ? parseFloat(detail.pod_order_qty) : null,
        pod_unit_price: detail.pod_unit_price ? parseFloat(detail.pod_unit_price) : null,
        pod_gross_amt: detail.pod_gross_amt ? parseFloat(detail.pod_gross_amt) : null,
        pod_discount: detail.pod_discount ? parseFloat(detail.pod_discount) : null,
        pod_total_amt: detail.pod_total_amt ? parseFloat(detail.pod_total_amt) : null,
        pod_total_invoiced: detail.pod_total_invoiced ? parseFloat(detail.pod_total_invoiced) : null,
        pod_total_paid: detail.pod_total_paid ? parseFloat(detail.pod_total_paid) : null,
        pod_item_spec: detail.pod_item_spec || null,
        pod_status: detail.pod_status || null,
        pod_request_no: detail.pod_request_no || null,
        pod_received_qty: detail.pod_received_qty ? parseFloat(detail.pod_received_qty) : null,
        pod_uom: detail.pod_uom || null,
        pod_crnote_amt: detail.pod_crnote_amt ? parseFloat(detail.pod_crnote_amt) : null,
        pod_lib_seq: detail.pod_lib_seq || null,
        so_code: detail.so_code || null,
        cpa_project_no: detail.cpa_project_no || null,
        pod_pakej_no: detail.pod_pakej_no ? parseFloat(detail.pod_pakej_no) : null,
        itm_item_no: detail.itm_item_no ? parseFloat(detail.itm_item_no) : null,
        pod_brand: detail.pod_brand || null,
        cny_country_code: detail.cny_country_code || null,
        pod_taxcode: detail.pod_taxcode || null,
        pod_taxpct: detail.pod_taxpct ? parseFloat(detail.pod_taxpct) : null,
        pod_taxamt: detail.pod_taxamt ? parseFloat(detail.pod_taxamt) : null,
        ccr_costcentre: detail.ccr_costcentre || null,
        pod_ccr_costcentre_budget: detail.pod_ccr_costcentre_budget || null,
        fty_fund_type: detail.fty_fund_type || null,
        at_activity_code: detail.at_activity_code || null,
        pod_at_activity_code_budget: detail.pod_at_activity_code_budget || null,
        sbg_budget_id: detail.sbg_budget_id || null,
        pod_ent_amt: detail.pod_ent_amt ? parseFloat(detail.pod_ent_amt) : null,
        pod_total_amtrm: detail.pod_total_amtrm ? parseFloat(detail.pod_total_amtrm) : null,
        pod_req_no: detail.pod_req_no || null,
        rqd_requisition_id: detail.rqd_requisition_id || null,
        pod_flag_manual: detail.pod_flag_manual || null,
        pod_cn_amount_ent: detail.pod_cn_amount_ent ? parseFloat(detail.pod_cn_amount_ent) : null,
        pod_cn_amount: detail.pod_cn_amount ? parseFloat(detail.pod_cn_amount) : null,
        createdby: user.username || 'system',
        updatedby: user.username || 'system',
      }));
      
      await prisma.purchase_order_details.createMany({
        data: detailsData,
      });
    }
    
    return {
      statusCode: 201,
      message: "Purchase order created successfully",
      data: {
        pom_order_id: purchaseOrder.pom_order_id,
        pom_order_no: purchaseOrder.pom_order_no,
      },
    };
  } catch (error) {
    console.error("Error creating purchase order:", error);
    return {
      statusCode: 500,
      message: "Failed to create purchase order",
      error: error.message,
    };
  }
});
