import prisma from "~/server/utils/prisma";

export default defineEventHandler(async (event) => {
  try {
    const body = await readBody(event);
    
    // Validate required fields
    if (!body.rqm_request_by || !body.rqm_request_date || !body.rqm_requisition_title) {
      return {
        statusCode: 400,
        message: "Required fields are missing",
        data: null,
      };
    }
    
    // Get the current user from session (adjust based on your auth implementation)
    const user = event.context.user || { username: 'system' };
    
    // Create requisition master
    const requisition = await prisma.requisition_master.create({
      data: {
        rqm_requisition_no: null, // Will be generated by database or sequence
        org_code: body.org_code || null,
        oun_code: body.oun_code || null,
        fty_fund_type: body.fty_fund_type || null,
        ccr_costcentre: body.ccr_costcentre || '',
        at_activity_code: body.at_activity_code || null,
        so_code: body.so_code || null,
        cpa_project_no: body.cpa_project_no || null,
        rqm_requisition_title: body.rqm_requisition_title,
        rqm_tender_scope: body.rqm_justification || null,
        rqm_tender_type: body.rqm_requisition_type || null,
        rqm_jenis_tender: body.rqm_jenis_tender || null,
        rqm_conversion_rate: body.rqm_conversion_rate ? parseFloat(body.rqm_conversion_rate) : null,
        rqm_currency_unit: body.rqm_conversion_unit ? parseFloat(body.rqm_conversion_unit) : null,
        rqm_currency_code: body.rqm_currency_code || null,
        rqm_rate_type: body.rqm_rate_type || null,
        rqm_rate_date: body.rqm_rate_date ? new Date(body.rqm_rate_date) : null,
        rqm_ent_amt: body.rqm_enter_amount ? parseFloat(body.rqm_enter_amount) : null,
        rqm_amount: body.rqm_total_amount ? parseFloat(body.rqm_total_amount) : null,
        rqm_total_gst: body.rqm_total_gst ? parseFloat(body.rqm_total_gst) : null,
        rqm_balance_bdgt: body.rqm_balance_bdgt ? parseFloat(body.rqm_balance_bdgt) : null,
        rqm_status: body.rqm_status || 'DRAFT',
        rqm_wflow_sts: body.rqm_wflow_sts || null,
        rqm_wflow_type: body.rqm_wflow_type || null,
        rqm_request_by: body.rqm_request_by,
        rqm_request_date: body.rqm_request_date ? new Date(body.rqm_request_date) : new Date(),
        rqm_ref_no: body.rqm_document_no || null,
        rqm_shipto_id: body.rqm_shipto_id || null,
        rqm_contact_person: body.rqm_contact_person || null,
        rqm_flag_bill: body.rqm_flag_bill || null,
        rqm_open: body.rqm_open || null,
        rqm_bumiputera: body.rqm_bumiputera || null,
        rqm_reg_no: body.rqm_reg_no || null,
        rqm_cctr_type: body.rqm_cctr_type || null,
        rqm_multi_cctr: body.rqm_multi_cctr || null,
        rqm_isagreement_exist: body.rqm_agreement || 'N',
        rqm_agg_no: body.rqm_agg_no || null,
        rqm_payee_code: body.rqm_vendor || null,
        createdby: user.username || 'system',
        updatedby: user.username || 'system',
      },
    });
    
    // Create requisition details if provided
    if (body.requisition_details && Array.isArray(body.requisition_details) && body.requisition_details.length > 0) {
      const detailsData = body.requisition_details.map((detail, index) => ({
        rqd_requisition_id: index + 1,
        rqm_requisition_id: requisition.rqm_requisition_id,
        rqd_line_no: detail.rqd_line_no ? parseFloat(detail.rqd_line_no) : index + 1,
        rqd_spec_desc: detail.rqd_spec_desc || null,
        rqd_pakej_no: detail.rqd_pakej_no || null,
        rqd_item_no: detail.rqd_item_no ? parseFloat(detail.rqd_item_no) : null,
        rqd_spec_level: detail.rqd_spec_level || null,
        rqd_spec_head: detail.rqd_spec_head || null,
        itm_item_code: detail.itm_item_code || null,
        rqd_qty: detail.rqd_qty || null,
        rqd_uom: detail.rqd_uom || null,
        rqd_price: detail.rqd_price ? parseFloat(detail.rqd_price) : null,
        rqd_gross_amt: detail.rqd_gross_amt ? parseFloat(detail.rqd_gross_amt) : null,
        rqd_ent_amt: detail.rqd_ent_amt ? parseFloat(detail.rqd_ent_amt) : null,
        rqd_total_price: detail.rqd_total_price ? parseFloat(detail.rqd_total_price) : null,
        rqd_total_price_rm: detail.rqd_total_price_rm ? parseFloat(detail.rqd_total_price_rm) : null,
        org_code: detail.org_code || null,
        fty_fund_type: detail.fty_fund_type || null,
        oun_code: detail.oun_code || null,
        at_activity_code: detail.at_activity_code || null,
        ccr_costcentre: detail.ccr_costcentre || null,
        so_code: detail.so_code || null,
        cpa_project_no: detail.cpa_project_no || null,
        bdg_budget_code: detail.bdg_budget_code || null,
        acm_acct_code: detail.acm_acct_code || null,
        rqd_ccr_costcentre_budget: detail.rqd_ccr_costcentre_budget || null,
        sbg_budget_id: detail.sbg_budget_id || null,
        rqd_at_activity_code_budget: detail.rqd_at_activity_code_budget || null,
        rqd_commit_amt: detail.rqd_commit_amt ? parseFloat(detail.rqd_commit_amt) : null,
        rqd_vot: detail.rqd_vot || null,
        rqd_taxcode: detail.rqd_taxcode || null,
        rqd_taxpct: detail.rqd_taxpct ? parseFloat(detail.rqd_taxpct) : null,
        rqd_taxamt: detail.rqd_taxamt ? parseFloat(detail.rqd_taxamt) : null,
        rqd_status: detail.rqd_status || null,
        createdby: user.username || 'system',
        updatedby: user.username || 'system',
      }));
      
      await prisma.requisition_details.createMany({
        data: detailsData,
      });
    }
    
    return {
      statusCode: 201,
      message: "Requisition created successfully",
      data: {
        rqm_requisition_id: requisition.rqm_requisition_id,
        rqm_requisition_no: requisition.rqm_requisition_no,
      },
    };
  } catch (error) {
    console.error("Error creating requisition:", error);
    return {
      statusCode: 500,
      message: "Failed to create requisition",
      error: error.message,
    };
  }
});
