// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/accountcode/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accountcode/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accountcode/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accountcode/[id].put').default>>>>
    }
    '/api/accountcode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accountcode/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accountcode/index.post').default>>>>
    }
    '/api/adm-message-log': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/adm-message-log/index.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.get').default>>>>
    }
    '/api/auth/validate': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/validate.get').default>>>>
    }
    '/api/budget/budget-closing/fund-types': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/budget-closing/fund-types.get').default>>>>
    }
    '/api/budget/budget-closing/reverse-process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/budget-closing/reverse-process.post').default>>>>
    }
    '/api/budget/budget-closing/start-process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/budget-closing/start-process.post').default>>>>
    }
    '/api/budget/budget-listing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/budget-listing/index.get').default>>>>
    }
    '/api/budget/decrement-v2-form/detail': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail.put').default>>>>
    }
    '/api/budget/decrement-v2-form/detail/get-budget': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail/get-budget.get').default>>>>
    }
    '/api/budget/decrement-v2-form/detail/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/detail/get.get').default>>>>
    }
    '/api/budget/decrement-v2-form/lookups/budget-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/lookups/budget-codes.get').default>>>>
    }
    '/api/budget/decrement-v2-form/master': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/master.get').default>>>>
    }
    '/api/budget/decrement-v2-form/new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/new.post').default>>>>
    }
    '/api/budget/decrement-v2-form/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/process-flow.get').default>>>>
    }
    '/api/budget/decrement-v2-form/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement-v2-form/submit.post').default>>>>
    }
    '/api/budget/decrement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/decrement/index.get').default>>>>
    }
    '/api/budget/increment-v2-form/detail': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail.put').default>>>>
    }
    '/api/budget/increment-v2-form/detail/get-budget': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail/get-budget.get').default>>>>
    }
    '/api/budget/increment-v2-form/detail/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/detail/get.get').default>>>>
    }
    '/api/budget/increment-v2-form/lookups/budget-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/lookups/budget-codes.get').default>>>>
    }
    '/api/budget/increment-v2-form/lookups/quarters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/lookups/quarters.get').default>>>>
    }
    '/api/budget/increment-v2-form/master': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/master.get').default>>>>
    }
    '/api/budget/increment-v2-form/new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/new.post').default>>>>
    }
    '/api/budget/increment-v2-form/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/process-flow.get').default>>>>
    }
    '/api/budget/increment-v2-form/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment-v2-form/submit.post').default>>>>
    }
    '/api/budget/increment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/increment/index.get').default>>>>
    }
    '/api/budget/initial': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/initial/index.get').default>>>>
    }
    '/api/budget/initial/lookups/quarters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/initial/lookups/quarters.get').default>>>>
    }
    '/api/budget/initial/lookups/statuses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/initial/lookups/statuses.get').default>>>>
    }
    '/api/budget/initial/lookups/years': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/initial/lookups/years.get').default>>>>
    }
    '/api/budget/monitoring': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/monitoring/index.get').default>>>>
    }
    '/api/budget/new-initial-v2/detail': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/detail.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/detail.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/detail.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/detail.put').default>>>>
    }
    '/api/budget/new-initial-v2/detail/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/detail/get.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/activities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/activities.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/budget-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/budget-codes.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/cost-centres': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/cost-centres.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/fund-types': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/fund-types.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/ptjs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/ptjs.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/quarters': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/quarters.get').default>>>>
    }
    '/api/budget/new-initial-v2/lookups/years': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/lookups/years.get').default>>>>
    }
    '/api/budget/new-initial-v2/master': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/master.get').default>>>>
    }
    '/api/budget/new-initial-v2/new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/new.post').default>>>>
    }
    '/api/budget/new-initial-v2/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/process-flow.get').default>>>>
    }
    '/api/budget/new-initial-v2/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/new-initial-v2/submit.post').default>>>>
    }
    '/api/budget/planning/budget-planning-allocation-2-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/budget-planning-allocation-2-list/index.get').default>>>>
    }
    '/api/budget/planning/budget-planning-allocation-3-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/budget-planning-allocation-3-list/index.get').default>>>>
    }
    '/api/budget/planning/dasar-sedia-ada/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/dasar-sedia-ada/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/dasar-sedia-ada/[id].get').default>>>>
    }
    '/api/budget/planning/dasar-sedia-ada': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/dasar-sedia-ada/index.get').default>>>>
    }
    '/api/budget/planning/new-application': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/new-application/index.post').default>>>>
    }
    '/api/budget/planning/report/abm-4': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/abm-4/index.get').default>>>>
    }
    '/api/budget/planning/report/abm-5': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/abm-5/index.get').default>>>>
    }
    '/api/budget/planning/report/abm-7': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/abm-7/index.get').default>>>>
    }
    '/api/budget/planning/report/abm-justfikasi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/abm-justfikasi/index.get').default>>>>
    }
    '/api/budget/planning/report/lampiran-abm-7': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/lampiran-abm-7/index.get').default>>>>
    }
    '/api/budget/planning/report/lookups/fund-type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/lookups/fund-type.get').default>>>>
    }
    '/api/budget/planning/report/lookups/ptj': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/lookups/ptj.get').default>>>>
    }
    '/api/budget/planning/report/lookups/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/lookups/status.get').default>>>>
    }
    '/api/budget/planning/report/lookups/vot-type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/planning/report/lookups/vot-type.get').default>>>>
    }
    '/api/budget/report/budget-report-by-account/allocation-expenditure-balance-by-budget-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/budget-report-by-account/allocation-expenditure-balance-by-budget-code/index.get').default>>>>
    }
    '/api/budget/report/budget-report-by-account/budget-summary-by-account-code-wbr072': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/budget-report-by-account/budget-summary-by-account-code-wbr072/index.get').default>>>>
    }
    '/api/budget/report/budget-report-by-ptj/variation-report-wbr074': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/budget-report-by-ptj/variation-report-wbr074/index.get').default>>>>
    }
    '/api/budget/report/laporan-belanjawan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/laporan-belanjawan/index.get').default>>>>
    }
    '/api/budget/report/lookups/years': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/lookups/years.get').default>>>>
    }
    '/api/budget/report/total-allocation-expenditure-balance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/total-allocation-expenditure-balance/index.get').default>>>>
    }
    '/api/budget/report/warrant/warrant-decrement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/warrant/warrant-decrement/index.get').default>>>>
    }
    '/api/budget/report/warrant/warrant-increment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/warrant/warrant-increment/index.get').default>>>>
    }
    '/api/budget/report/warrant/warrant-initial': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/warrant/warrant-initial/index.get').default>>>>
    }
    '/api/budget/report/warrant/warrant-virement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/report/warrant/warrant-virement/index.get').default>>>>
    }
    '/api/budget/setup/allocation/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/allocation/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/allocation/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/allocation/[id].put').default>>>>
    }
    '/api/budget/setup/allocation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/allocation/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/allocation/index.post').default>>>>
    }
    '/api/budget/setup/budget-code/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-code/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-code/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-code/[id].put').default>>>>
    }
    '/api/budget/setup/budget-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-code/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-code/index.post').default>>>>
    }
    '/api/budget/setup/budget-planning-schedule/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-planning-schedule/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-planning-schedule/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-planning-schedule/[id].put').default>>>>
    }
    '/api/budget/setup/budget-planning-schedule': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-planning-schedule/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-planning-schedule/index.post').default>>>>
    }
    '/api/budget/setup/budget-structure-list/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-structure-list/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-structure-list/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-structure-list/[id].put').default>>>>
    }
    '/api/budget/setup/budget-structure-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-structure-list/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/setup/budget-structure-list/index.post').default>>>>
    }
    '/api/budget/virement-v2-form/detail': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail.put').default>>>>
    }
    '/api/budget/virement-v2-form/detail/from': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail/from.get').default>>>>
    }
    '/api/budget/virement-v2-form/detail/get-budget': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail/get-budget.get').default>>>>
    }
    '/api/budget/virement-v2-form/detail/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail/get.get').default>>>>
    }
    '/api/budget/virement-v2-form/detail/to': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/detail/to.get').default>>>>
    }
    '/api/budget/virement-v2-form/lookups/budget-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/lookups/budget-codes.get').default>>>>
    }
    '/api/budget/virement-v2-form/lookups/currency-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/lookups/currency-codes.get').default>>>>
    }
    '/api/budget/virement-v2-form/lookups/movement-types': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/lookups/movement-types.get').default>>>>
    }
    '/api/budget/virement-v2-form/master': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/master.get').default>>>>
    }
    '/api/budget/virement-v2-form/new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/new.post').default>>>>
    }
    '/api/budget/virement-v2-form/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/process-flow.get').default>>>>
    }
    '/api/budget/virement-v2-form/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement-v2-form/submit.post').default>>>>
    }
    '/api/budget/virement': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budget/virement/index.get').default>>>>
    }
    '/api/component-editor/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/[id].put').default>>>>
    }
    '/api/component-editor/available-pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/available-pages.get').default>>>>
    }
    '/api/component-editor/helpers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/helpers').default>>>>
    }
    '/api/component-editor/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/import.post').default>>>>
    }
    '/api/component-editor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/index.post').default>>>>
    }
    '/api/component-editor/migration-files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-editor/migration-files.get').default>>>>
    }
    '/api/component-item-editor/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/[id].put').default>>>>
    }
    '/api/component-item-editor/helpers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/helpers').default>>>>
    }
    '/api/component-item-editor/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/import.post').default>>>>
    }
    '/api/component-item-editor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/index.post').default>>>>
    }
    '/api/component-item-editor/migration-files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/component-item-editor/migration-files.get').default>>>>
    }
    '/api/devtool/api/file-code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/api/file-code').default>>>>
    }
    '/api/devtool/api/linter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/api/linter').default>>>>
    }
    '/api/devtool/api/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/api/list').default>>>>
    }
    '/api/devtool/api/prettier-format': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/api/prettier-format').default>>>>
    }
    '/api/devtool/api/save': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/api/save').default>>>>
    }
    '/api/devtool/config/add-custom-theme': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/config/add-custom-theme').default>>>>
    }
    '/api/devtool/config/env': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/config/env').default>>>>
    }
    '/api/devtool/config/loading-logo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/config/loading-logo').default>>>>
    }
    '/api/devtool/config/site-settings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/config/site-settings').default>>>>
    }
    '/api/devtool/config/upload-file': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/config/upload-file').default>>>>
    }
    '/api/devtool/content/canvas/file-code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/canvas/file-code').default>>>>
    }
    '/api/devtool/content/code/file-code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/code/file-code').default>>>>
    }
    '/api/devtool/content/code/linter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/code/linter').default>>>>
    }
    '/api/devtool/content/code/prettier-format': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/code/prettier-format').default>>>>
    }
    '/api/devtool/content/code/save': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/code/save').default>>>>
    }
    '/api/devtool/content/template/get-list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/template/get-list').default>>>>
    }
    '/api/devtool/content/template/import': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/template/import').default>>>>
    }
    '/api/devtool/content/template/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/template/list').default>>>>
    }
    '/api/devtool/content/template/tag': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/content/template/tag').default>>>>
    }
    '/api/devtool/lookup/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/lookup/list').default>>>>
    }
    '/api/devtool/menu/add': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/add').default>>>>
    }
    '/api/devtool/menu/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/delete').default>>>>
    }
    '/api/devtool/menu/edit': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/edit').default>>>>
    }
    '/api/devtool/menu/new-add': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/new-add').default>>>>
    }
    '/api/devtool/menu/overwrite-navigation': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/overwrite-navigation').default>>>>
    }
    '/api/devtool/menu/role-list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/role-list').default>>>>
    }
    '/api/devtool/menu/user-list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/menu/user-list').default>>>>
    }
    '/api/devtool/orm/data/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/data/get.get').default>>>>
    }
    '/api/devtool/orm/schema': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/schema.get').default>>>>
    }
    '/api/devtool/orm/studio': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/studio.get').default>>>>
    }
    '/api/devtool/orm/table/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/table/config/index.get').default>>>>
    }
    '/api/devtool/orm/table/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/table/create/index.post').default>>>>
    }
    '/api/devtool/orm/table/delete/:table': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/table/delete/[table]/index.delete').default>>>>
    }
    '/api/devtool/orm/table/modify/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/table/modify/get.get').default>>>>
    }
    '/api/devtool/orm/table/modify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/orm/table/modify/index.post').default>>>>
    }
    '/api/devtool/role/add': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/role/add').default>>>>
    }
    '/api/devtool/role/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/role/delete').default>>>>
    }
    '/api/devtool/role/edit': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/role/edit').default>>>>
    }
    '/api/devtool/role/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/role/list').default>>>>
    }
    '/api/devtool/user/add': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/user/add').default>>>>
    }
    '/api/devtool/user/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/user/delete').default>>>>
    }
    '/api/devtool/user/edit': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/user/edit').default>>>>
    }
    '/api/devtool/user/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devtool/user/list').default>>>>
    }
    '/api/fundtype/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fundtype/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fundtype/[id].put').default>>>>
    }
    '/api/fundtype': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fundtype/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fundtype/index.post').default>>>>
    }
    '/api/message-log': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/message-log.post').default>>>>
    }
    '/api/metabase/token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/metabase/token.get').default>>>>
    }
    '/api/page-editor/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/[id].put').default>>>>
    }
    '/api/page-editor/available-menus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/available-menus.get').default>>>>
    }
    '/api/page-editor/helpers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/helpers').default>>>>
    }
    '/api/page-editor/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/import.post').default>>>>
    }
    '/api/page-editor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/index.post').default>>>>
    }
    '/api/page-editor/migration-files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page-editor/migration-files.get').default>>>>
    }
    '/api/penyuntingmuka/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/[id].put').default>>>>
    }
    '/api/penyuntingmuka/helpers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/helpers').default>>>>
    }
    '/api/penyuntingmuka': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/index.post').default>>>>
    }
    '/api/penyuntingmuka/next-id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/penyuntingmuka/next-id.get').default>>>>
    }
    '/api/posting-to-gl/credit-details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/credit-details.get').default>>>>
    }
    '/api/posting-to-gl/debit-details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/debit-details.get').default>>>>
    }
    '/api/posting-to-gl/display-master': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/display-master.get').default>>>>
    }
    '/api/posting-to-gl': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/index.get').default>>>>
    }
    '/api/posting-to-gl/statuses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/statuses.get').default>>>>
    }
    '/api/posting-to-gl/system-ids': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posting-to-gl/system-ids.get').default>>>>
    }
    '/api/purchasing/advertisement/committee-report': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/advertisement/committee-report/index.get').default>>>>
    }
    '/api/purchasing/advertisement/duration-tender-quotation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/advertisement/duration-tender-quotation/index.get').default>>>>
    }
    '/api/purchasing/advertisement/new-tender-quotation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/advertisement/new-tender-quotation/index.get').default>>>>
    }
    '/api/purchasing/advertisement/request-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/advertisement/request-list/index.get').default>>>>
    }
    '/api/purchasing/agreement/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/agreement/list/index.get').default>>>>
    }
    '/api/purchasing/bank-guarantee/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/bank-guarantee/list/index.get').default>>>>
    }
    '/api/purchasing/good-receive-note/cancel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/good-receive-note/cancel/index.get').default>>>>
    }
    '/api/purchasing/good-receive-note/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/good-receive-note/list/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/[id].put').default>>>>
    }
    '/api/purchasing/purchase-order/:id/pr-items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/[id]/pr-items.get').default>>>>
    }
    '/api/purchasing/purchase-order/:id/pr-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/[id]/pr-list.get').default>>>>
    }
    '/api/purchasing/purchase-order/:id/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/[id]/process-flow.get').default>>>>
    }
    '/api/purchasing/purchase-order/cancel-po-partial-listing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/cancel-po-partial-listing/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-closed-reverse/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-closed-reverse/confirm.post').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-closed-reverse': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-closed-reverse/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-confirmation-process-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-confirmation-process-list/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-confirmation-process/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-confirmation-process/[id].get').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-confirmation-process/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-confirmation-process/confirm.post').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-confirmation-process': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-confirmation-process/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/closing/po-confirmation-process/process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/po-confirmation-process/process.post').default>>>>
    }
    '/api/purchasing/purchase-order/closing/process-closing/po-process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/process-closing/po-process.post').default>>>>
    }
    '/api/purchasing/purchase-order/closing/process-closing/po-reverse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/closing/process-closing/po-reverse.post').default>>>>
    }
    '/api/purchasing/purchase-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/index.post').default>>>>
    }
    '/api/purchasing/purchase-order/list-cancellation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/list-cancellation/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/list/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/new-cancel-po-partial': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/new-cancel-po-partial/index.get').default>>>>
    }
    '/api/purchasing/purchase-order/new-cancellation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-order/new-cancellation/index.get').default>>>>
    }
    '/api/purchasing/purchase-requisition/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/[id].put').default>>>>
    }
    '/api/purchasing/purchase-requisition/:id/process-flow': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/[id]/process-flow.get').default>>>>
    }
    '/api/purchasing/purchase-requisition': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/index.post').default>>>>
    }
    '/api/purchasing/purchase-requisition/list-cancel-pr-partial': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/list-cancel-pr-partial/index.get').default>>>>
    }
    '/api/purchasing/purchase-requisition/list-cancellation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/list-cancellation/index.get').default>>>>
    }
    '/api/purchasing/purchase-requisition/list-pr-to-be-cancel-partial': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/list-pr-to-be-cancel-partial/index.get').default>>>>
    }
    '/api/purchasing/purchase-requisition/list-pr-to-be-cancel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/list-pr-to-be-cancel/index.get').default>>>>
    }
    '/api/purchasing/purchase-requisition/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/purchase-requisition/list/index.get').default>>>>
    }
    '/api/purchasing/report-po/bendahari': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report-po/bendahari/index.get').default>>>>
    }
    '/api/purchasing/report-po/ptj': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report-po/ptj/index.get').default>>>>
    }
    '/api/purchasing/report/laporan-lppm-jpka-kpt/perolehan-melalui-kontrak-pusat-sistem-panel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report/laporan-lppm-jpka-kpt/perolehan-melalui-kontrak-pusat-sistem-panel/index.get').default>>>>
    }
    '/api/purchasing/report/laporan-perolehan-ptj-jpka-lppm/laporan-keseluruhan-perolehan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report/laporan-perolehan-ptj-jpka-lppm/laporan-keseluruhan-perolehan/index.get').default>>>>
    }
    '/api/purchasing/report/laporan-perolehan-ptj-jpka-lppm/senarai-tempoh-masa-lpo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report/laporan-perolehan-ptj-jpka-lppm/senarai-tempoh-masa-lpo/index.get').default>>>>
    }
    '/api/purchasing/report/vendor-assessment-grn': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/report/vendor-assessment-grn/index.get').default>>>>
    }
    '/api/purchasing/setup/assessment-question': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/assessment-question/index.get').default>>>>
    }
    '/api/purchasing/setup/item-main-listing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main-listing/index.get').default>>>>
    }
    '/api/purchasing/setup/item-main/group-lookup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/group-lookup.get').default>>>>
    }
    '/api/purchasing/setup/item-main': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/index.get').default>>>>
    }
    '/api/purchasing/setup/item-main/item-main-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/item-main-list.get').default>>>>
    }
    '/api/purchasing/setup/item-main/main-category': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/main-category.get').default>>>>
    }
    '/api/purchasing/setup/item-main/subcategory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/subcategory.get').default>>>>
    }
    '/api/purchasing/setup/item-main/subsiri': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/item-main/subsiri.get').default>>>>
    }
    '/api/purchasing/setup/list-of-jobscope': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/setup/list-of-jobscope/index.get').default>>>>
    }
    '/api/purchasing/status-po-pr': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/status-po-pr/index.get').default>>>>
    }
    '/api/purchasing/status-po-pr/po-status-options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/status-po-pr/po-status-options.get').default>>>>
    }
    '/api/purchasing/tender-quotation/advertisement-complete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/advertisement-complete/index.get').default>>>>
    }
    '/api/purchasing/tender-quotation/cancellation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/cancellation/index.get').default>>>>
    }
    '/api/purchasing/tender-quotation/committee-participant': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/committee-participant/index.get').default>>>>
    }
    '/api/purchasing/tender-quotation/evaluation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/evaluation/index.get').default>>>>
    }
    '/api/purchasing/tender-quotation/generated-offer-letter': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/generated-offer-letter/index.get').default>>>>
    }
    '/api/purchasing/tender-quotation/selection': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/tender-quotation/selection/index.get').default>>>>
    }
    '/api/purchasing/variation-order/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/variation-order/list/index.get').default>>>>
    }
    '/api/purchasing/vendor-assessment/good-receive-note': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/vendor-assessment/good-receive-note/index.get').default>>>>
    }
    '/api/purchasing/vendor-assessment/work-progress-note': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/vendor-assessment/work-progress-note/index.get').default>>>>
    }
    '/api/purchasing/vendor/bank-account-update': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/vendor/bank-account-update/index.get').default>>>>
    }
    '/api/purchasing/vendor/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/vendor/list/index.get').default>>>>
    }
    '/api/purchasing/vendor/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/vendor/profile/index.get').default>>>>
    }
    '/api/purchasing/work-progress-note/cancel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/work-progress-note/cancel/index.get').default>>>>
    }
    '/api/purchasing/work-progress-note/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/work-progress-note/detail/index.get').default>>>>
    }
    '/api/purchasing/work-progress-note/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchasing/work-progress-note/list/index.get').default>>>>
    }
    '/api/setup/account-code/:code': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/[code].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/[code].put').default>>>>
    }
    '/api/setup/account-code/activity/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/activity/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/activity/[id].put').default>>>>
    }
    '/api/setup/account-code/activity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/activity/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/activity/index.post').default>>>>
    }
    '/api/setup/account-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/account-code/index.post').default>>>>
    }
    '/api/setup/activity-code/activity-type/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/activity-type/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/activity-type/[id].put').default>>>>
    }
    '/api/setup/activity-code/activity-type': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/activity-type/index.post').default>>>>
    }
    '/api/setup/activity-code/group/:code': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/group/[code].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/group/[code].put').default>>>>
    }
    '/api/setup/activity-code/group': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/group/index.post').default>>>>
    }
    '/api/setup/activity-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/index.get').default>>>>
    }
    '/api/setup/activity-code/subgroup/:code': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subgroup/[code].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subgroup/[code].put').default>>>>
    }
    '/api/setup/activity-code/subgroup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subgroup/index.post').default>>>>
    }
    '/api/setup/activity-code/subsiri/:code': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subsiri/[code].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subsiri/[code].put').default>>>>
    }
    '/api/setup/activity-code/subsiri': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/activity-code/subsiri/index.post').default>>>>
    }
    '/api/setup/cascade-structure/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/[id].put').default>>>>
    }
    '/api/setup/cascade-structure/autosuggest-activity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/autosuggest-activity.get').default>>>>
    }
    '/api/setup/cascade-structure/autosuggest-costcentre': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/autosuggest-costcentre.get').default>>>>
    }
    '/api/setup/cascade-structure/autosuggest-fund': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/autosuggest-fund.get').default>>>>
    }
    '/api/setup/cascade-structure/autosuggest-ptj': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/autosuggest-ptj.get').default>>>>
    }
    '/api/setup/cascade-structure': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cascade-structure/index.post').default>>>>
    }
    '/api/setup/cost-centre/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/[id].put').default>>>>
    }
    '/api/setup/cost-centre/autosuggest-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/autosuggest-code.get').default>>>>
    }
    '/api/setup/cost-centre/autosuggest-ptj': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/autosuggest-ptj.get').default>>>>
    }
    '/api/setup/cost-centre': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/cost-centre/index.post').default>>>>
    }
    '/api/setup/ptj-code/:code': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/ptj-code/[code].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/ptj-code/[code].put').default>>>>
    }
    '/api/setup/ptj-code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/ptj-code/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup/ptj-code/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}