// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/plugin").default> &
  InjectionType<typeof import("../templates.pwa.client.e96e4076").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/@pinia-plugin-persistedstate/nuxt/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../plugins/apex-chart.client").default> &
  InjectionType<typeof import("../../plugins/chart-js.client").default> &
  InjectionType<typeof import("../../plugins/formkit-auto-animate").default> &
  InjectionType<typeof import("../../plugins/full-calendar.client").default> &
  InjectionType<typeof import("../../plugins/maska").default> &
  InjectionType<typeof import("../../plugins/recaptcha.client").default> &
  InjectionType<typeof import("../../plugins/site-settings.client").default> &
  InjectionType<typeof import("../../plugins/swiper").default> &
  InjectionType<typeof import("../../plugins/uid-plugin").default> &
  InjectionType<typeof import("../../plugins/v-select").default> &
  InjectionType<typeof import("../../plugins/vue-calendar").default> &
  InjectionType<typeof import("../../plugins/vue-code-highlight").default> &
  InjectionType<typeof import("../../plugins/vue-codemirror").default> &
  InjectionType<typeof import("../../plugins/vue-country-flag").default> &
  InjectionType<typeof import("../../plugins/vue-draggable.client").default> &
  InjectionType<typeof import("../../plugins/vue-fullscreen").default> &
  InjectionType<typeof import("../../plugins/vue-quill.client").default> &
  InjectionType<typeof import("../../plugins/vue-sweetalert2").default> &
  InjectionType<typeof import("../../plugins/vue-toastification.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
