
        
  // @ts-nocheck
  // eslint-disable
  /** 
  * ---------------------------------------------------
  * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
  * ---------------------------------------------------
  * */
 


        
    
    import type { NuxtLinkProps, PageMeta } from '#app';
    import NuxtLink from 'nuxt/dist/app/components/nuxt-link';
    import type { RouteLocationRaw, RouteLocationPathRaw } from 'vue-router';
    import type { RoutesNamedLocations, RoutesNamesListRecord, RoutesNamesList } from './__routes';
    import type {TypedRouter, TypedRoute, TypedRouteLocationRawFromName, TypedLocationAsRelativeRaw} from './__router';
    import { useRoute as _useRoute } from './__useTypedRoute';
    import { useRouter as _useRouter } from './__useTypedRouter';
    import { navigateTo as _navigateTo } from './__navigateTo';
    

    import {definePageMeta as _definePageMeta} from './__definePageMeta';

    import type {TypedPathParameter} from './__paths';


    declare global {
 
      
            const useRoute: typeof _useRoute;
            const useRouter: typeof _useRouter;
            const navigateTo: typeof _navigateTo;
            const definePageMeta: typeof _definePageMeta;
            
            
          
    }
    
    type TypedNuxtLinkProps<T extends string, E extends boolean = false> = Omit<NuxtLinkProps, 'to' | 'external'> &
     {
      to: 
        | Omit<Exclude<RouteLocationRaw, string>, 'name' | 'params'> & RoutesNamedLocations
        | Omit<RouteLocationPathRaw, 'path'>
        & {path?: (E extends true ? string : TypedPathParameter<T>)}
        
        
         | (E extends true ? string : TypedPathParameter<T>),
      external?: E
      }
    
        
          
    export type TypedNuxtLink = new <P extends string, E extends boolean = false>(props: TypedNuxtLinkProps<P, E>) => Omit<
      typeof NuxtLink,
      '$props'
    > & {
      $props: TypedNuxtLinkProps<P, E>;
    };
    
    // Declare runtime-core instead of vue for compatibility issues with pnpm
    declare module 'vue' {
      interface GlobalComponents {
        NuxtLink: TypedNuxtLink;
      }
    }

    
  
      